# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: asset-trail-backend_development

test:
  <<: *default
  database: asset-trail-backend_test

production:
  <<: *default
  database: asset-trail-backend_production
  username: asset-trail-backend
  password: <%= ENV['ASSET-TRAIL-BACKEND_DATABASE_PASSWORD'] %>
